name: add log from study-log
on:
  push:
    branches:
      - main
      - develop
  schedule:
    - cron: "10 15 * * *"
  workflow_dispatch:
jobs:
  add-study-log:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: check new commits in the last 24 hours
        run: |
          NOW=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          YESTERDAY=$(date -u -d "24 hours ago" +"%Y-%m-%dT%H:%M:%SZ")
          COMMITS=$(git log --since="$YESTERDAY" --until="$NOW" --pretty=format:"%H" | tr '\n' ',')
          echo "コミットは${COMMITS}"
          echo "commit_hashes=${COMMITS}" >> $GITHUB_ENV
          if [ -z "$COMMITS" ]; then
            echo "No commits found in the last 24 hours."
            echo "continue=false" >> $GITHUB_ENV
          else
            echo "Commits found:"
            echo "continue=true" >> $GITHUB_ENV
            echo "repo_name=${{ github.repository }}" >> $GITHUB_ENV
          fi


      - name: Print commit
        if: env.continue == 'true'
        run: |
          TIMESTAMP=$(date "+%Y-%m-%d")
          FILENAME="./study-log/${TIMESTAMP}.md"
          files=$(ls -la)
          echo "Files in the directory: $files"

          if [ ! -f "${FILENAME}" ]; then
            echo "Creating file: ${FILENAME}"
            touch "${FILENAME}"
          else
            echo "File already exists: ${FILENAME}"
          fi
  
          echo "## study-log 作業記録 ${TIMESTAMP}" >> ${FILENAME}
          IFS=',' read -r -a commits_array <<< "${{ env.commit_hashes }}"
          for commit in ${commits_array[@]}; do
            echo "- https://github.com/${{ env.repo_name }}/commit/${commit} <br>" >> ${FILENAME}
          done
          git config user.name "onishi-teppei"
          git config user.email "teppei99.nxw@gmail.com"
          git add ${FILENAME}
          git commit -m "Update study log with commits from the last 24 hours"
          git push origin main
