name: add log from management-invest
on:
  schedule:
    - cron: "25 19 * * *"
  workflow_dispatch:
jobs:
  add-study-log:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          repository: onishi-teppei/management_invest
          fetch-depth: 0
          token: ${{ secrets.ACCES_MY_REPO }}

      - name: Fetch all branches
        run: git fetch --all

      - name: check new commits in the last 24 hours
        run: |
          NOW=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          YESTERDAY=$(date -u -d "24 hours ago" +"%Y-%m-%dT%H:%M:%SZ")
          COMMITS=$(git log --all --since="$YESTERDAY" --until="$NOW" --author="onishi-teppei" --pretty=format:"%H" | tr '\n' ',')
          echo "commit_hashes=${COMMITS}" >> $GITHUB_ENV
          if [ -z "$COMMITS" ]; then
            echo "No commits found in the last 24 hours."
            echo "continue=false" >> $GITHUB_ENV
          else
            echo "Commits found:"
            echo "continue=true" >> $GITHUB_ENV
            echo "repo_name=onishi-teppei/management_invest" >> $GITHUB_ENV
          fi

      - name: Checkout this repo
        if: env.continue == 'true'
        uses: actions/checkout@v4
        with:
          repository: onishi-teppei/study-log
          ref: main
          fetch-depth: 1

      - name: Print commit
        if: env.continue == 'true'
        run: |
          TIMESTAMP=$(date "+%Y-%m-%d")
          FILENAME="./study-log/${TIMESTAMP}.md"

          if [ ! -f "${FILENAME}" ]; then
            echo "Creating file: ${FILENAME}"
            touch "${FILENAME}"
          else
            echo "File already exists: ${FILENAME}"
          fi

          echo "## management-invest 作業記録 ${TIMESTAMP}" >> ${FILENAME}
          IFS=',' read -r -a commits_array <<< "${{ env.commit_hashes }}"
          for commit in ${commits_array[@]}; do
            echo "- https://github.com/${{ env.repo_name }}/commit/${commit} <br>" >> ${FILENAME}
          done
          git config user.name "onishi-teppei"
          git config user.email "teppei99.nxw@gmail.com"
          git add ${FILENAME}
          git commit -m "Update study log with commits from the last 24 hours"
          git push origin main
