name: First Cron Job
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Run a one-line script
        run: echo Hello, world!