name: Cron test
on:
  push:
    branches:
      - main
      - develop
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:
jobs:
  add-study-log:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Check for new commits in the last 24 hours
        id: check_commits
        run: |
          NOW=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo "現在時刻は${NOW}"
          YESTERDAY=$(date -u -d "24 hours ago" +"%Y-%m-%dT%H:%M:%SZ")
          echo "日付は${YESTERDAY}"
          COMMITS=$(git log --since="$YESTERDAY" --until="$NOW" --pretty=format:"%H %s")
          echo "commitは${COMMITS}"
          if [ -z "$COMMITS" ]; then
            echo "No commits found in the last 24 hours."
            echo "::set-output name=has_commits::false"
          else
            echo "Commits found:"
            echo "$COMMITS"
            echo "::set-output name=has_commits::true"
            echo "::set-output name=commit_log::\"$COMMITS\""
          fi