name: Cron test
on:
  push:
    branches:
      - main
      - develop
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:
jobs:
  add-study-log:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 30

      - name: Check for new commits in the last 24 hours
        id: check_commits
        run: |
          NOW=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          YESTERDAY=$(date -u -d "24 hours ago" +"%Y-%m-%dT%H:%M:%SZ")
          COMMITS=$(git log --since="$YESTERDAY" --until="$NOW" --pretty=format:"%H %s")
          echo "commitは${COMMITS}"
          if [ -z "$COMMITS" ]; then
            echo "No commits found in the last 24 hours."
            echo "::set-output name=has_commits::false"
          else
            echo "Commits found:"
            echo "$COMMITS"
            echo "::set-output name=has_commits::true"
            echo "::set-output name=commit_log::\"$COMMITS\""
          fi

      # 4. 作業ログの更新
      - name: Update work log with commit details
        if: steps.check_commits.outputs.has_commits == 'true'
        run: |
          echo "書き込み実行"
          TIMESTAMP=$(date "+%Y-%m-%d %H:%M:%S")
          echo "## New work completed on ${TIMESTAMP}" >> study-log.md
          echo "${{ steps.check_commits.outputs.commit_log }}" >> study-log.md
          git config user.name "onishi-teppei"
          git config user.email "teppei99.nxw@gmail.com"
          git add ./study-log.md
          git commit -m "Update work log with commits from the last 24 hours"
          git push origin main  # 作業記録をデフォルトブランチにプッシュ