name: Update daily study log

on:
  schedule:
    - cron: "*/2 * * * *" 

jobs:
  dump-value:
    name: dump-value
    runs-on: ubuntu-latest
    steps:
      - name: echo hello
        run: echo 'hello teppei'